# Generated by Django 4.1.3 on 2022-12-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='profilesocialnetwork',
            options={'verbose_name': 'Profile Social Network', 'verbose_name_plural': 'Profile Social Networks'},
        ),
    ]
