# Generated by Django 4.1.3 on 2022-12-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_location_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
