# Generated by Django 4.1.3 on 2022-12-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profilesocialnetwork_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilesocialnetwork',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
