# Generated by Django 4.1.3 on 2022-11-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_count_project_vote_ratio_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
