# Generated by Django 4.1.3 on 2022-12-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
