# Generated by Django 4.1.3 on 2022-12-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0002_alter_socialnetwork_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
