# Generated by Django 4.1.3 on 2022-12-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0003_socialnetwork_css_class_socialnetwork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
